// Code generated by protoc-gen-go.
// source: riak_yokozuna.proto
// DO NOT EDIT!

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RpbYokozunaIndex struct {
	Name             []byte  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Schema           []byte  `protobuf:"bytes,2,opt,name=schema" json:"schema,omitempty"`
	NVal             *uint32 `protobuf:"varint,3,opt,name=n_val" json:"n_val,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpbYokozunaIndex) Reset()                    { *m = RpbYokozunaIndex{} }
func (m *RpbYokozunaIndex) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaIndex) ProtoMessage()               {}
func (*RpbYokozunaIndex) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *RpbYokozunaIndex) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RpbYokozunaIndex) GetSchema() []byte {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *RpbYokozunaIndex) GetNVal() uint32 {
	if m != nil && m.NVal != nil {
		return *m.NVal
	}
	return 0
}

// GET request - If a name is given, return matching index, else return all
type RpbYokozunaIndexGetReq struct {
	Name             []byte `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpbYokozunaIndexGetReq) Reset()                    { *m = RpbYokozunaIndexGetReq{} }
func (m *RpbYokozunaIndexGetReq) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaIndexGetReq) ProtoMessage()               {}
func (*RpbYokozunaIndexGetReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *RpbYokozunaIndexGetReq) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RpbYokozunaIndexGetResp struct {
	Index            []*RpbYokozunaIndex `protobuf:"bytes,1,rep,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *RpbYokozunaIndexGetResp) Reset()                    { *m = RpbYokozunaIndexGetResp{} }
func (m *RpbYokozunaIndexGetResp) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaIndexGetResp) ProtoMessage()               {}
func (*RpbYokozunaIndexGetResp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *RpbYokozunaIndexGetResp) GetIndex() []*RpbYokozunaIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

// PUT request - Create a new index
type RpbYokozunaIndexPutReq struct {
	Index            *RpbYokozunaIndex `protobuf:"bytes,1,req,name=index" json:"index,omitempty"`
	Timeout          *uint32           `protobuf:"varint,2,opt,name=timeout" json:"timeout,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RpbYokozunaIndexPutReq) Reset()                    { *m = RpbYokozunaIndexPutReq{} }
func (m *RpbYokozunaIndexPutReq) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaIndexPutReq) ProtoMessage()               {}
func (*RpbYokozunaIndexPutReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *RpbYokozunaIndexPutReq) GetIndex() *RpbYokozunaIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *RpbYokozunaIndexPutReq) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

// DELETE request - Remove an index
type RpbYokozunaIndexDeleteReq struct {
	Name             []byte `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpbYokozunaIndexDeleteReq) Reset()                    { *m = RpbYokozunaIndexDeleteReq{} }
func (m *RpbYokozunaIndexDeleteReq) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaIndexDeleteReq) ProtoMessage()               {}
func (*RpbYokozunaIndexDeleteReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *RpbYokozunaIndexDeleteReq) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RpbYokozunaSchema struct {
	Name             []byte `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Content          []byte `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpbYokozunaSchema) Reset()                    { *m = RpbYokozunaSchema{} }
func (m *RpbYokozunaSchema) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaSchema) ProtoMessage()               {}
func (*RpbYokozunaSchema) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *RpbYokozunaSchema) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RpbYokozunaSchema) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// PUT request - create or potentially update a new schema
type RpbYokozunaSchemaPutReq struct {
	Schema           *RpbYokozunaSchema `protobuf:"bytes,1,req,name=schema" json:"schema,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *RpbYokozunaSchemaPutReq) Reset()                    { *m = RpbYokozunaSchemaPutReq{} }
func (m *RpbYokozunaSchemaPutReq) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaSchemaPutReq) ProtoMessage()               {}
func (*RpbYokozunaSchemaPutReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *RpbYokozunaSchemaPutReq) GetSchema() *RpbYokozunaSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

// GET request - Return matching schema by name
type RpbYokozunaSchemaGetReq struct {
	Name             []byte `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpbYokozunaSchemaGetReq) Reset()                    { *m = RpbYokozunaSchemaGetReq{} }
func (m *RpbYokozunaSchemaGetReq) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaSchemaGetReq) ProtoMessage()               {}
func (*RpbYokozunaSchemaGetReq) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *RpbYokozunaSchemaGetReq) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RpbYokozunaSchemaGetResp struct {
	Schema           *RpbYokozunaSchema `protobuf:"bytes,1,req,name=schema" json:"schema,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *RpbYokozunaSchemaGetResp) Reset()                    { *m = RpbYokozunaSchemaGetResp{} }
func (m *RpbYokozunaSchemaGetResp) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaSchemaGetResp) ProtoMessage()               {}
func (*RpbYokozunaSchemaGetResp) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *RpbYokozunaSchemaGetResp) GetSchema() *RpbYokozunaSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func init() {
	proto.RegisterType((*RpbYokozunaIndex)(nil), "protobuf.RpbYokozunaIndex")
	proto.RegisterType((*RpbYokozunaIndexGetReq)(nil), "protobuf.RpbYokozunaIndexGetReq")
	proto.RegisterType((*RpbYokozunaIndexGetResp)(nil), "protobuf.RpbYokozunaIndexGetResp")
	proto.RegisterType((*RpbYokozunaIndexPutReq)(nil), "protobuf.RpbYokozunaIndexPutReq")
	proto.RegisterType((*RpbYokozunaIndexDeleteReq)(nil), "protobuf.RpbYokozunaIndexDeleteReq")
	proto.RegisterType((*RpbYokozunaSchema)(nil), "protobuf.RpbYokozunaSchema")
	proto.RegisterType((*RpbYokozunaSchemaPutReq)(nil), "protobuf.RpbYokozunaSchemaPutReq")
	proto.RegisterType((*RpbYokozunaSchemaGetReq)(nil), "protobuf.RpbYokozunaSchemaGetReq")
	proto.RegisterType((*RpbYokozunaSchemaGetResp)(nil), "protobuf.RpbYokozunaSchemaGetResp")
}

var fileDescriptor4 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0xca, 0x4c, 0xcc,
	0x8e, 0xaf, 0xcc, 0xcf, 0xce, 0xaf, 0x2a, 0xcd, 0x4b, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0xf6, 0x5c, 0x02, 0x41, 0x05, 0x49, 0x91, 0x50, 0x69,
	0xcf, 0xbc, 0x94, 0xd4, 0x0a, 0x21, 0x1e, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05,
	0x26, 0x0d, 0x1e, 0x21, 0x3e, 0x2e, 0xb6, 0xe2, 0xe4, 0x8c, 0xd4, 0xdc, 0x44, 0x09, 0x26, 0x05,
	0x46, 0x20, 0x9f, 0x97, 0x8b, 0x35, 0x2f, 0xbe, 0x2c, 0x31, 0x47, 0x82, 0x19, 0xc8, 0xe5, 0x55,
	0x52, 0xe3, 0x12, 0x43, 0x37, 0xc0, 0x3d, 0xb5, 0x24, 0x28, 0xb5, 0x10, 0xc9, 0x18, 0xa0, 0x36,
	0x25, 0x17, 0x2e, 0x71, 0xac, 0xea, 0x8a, 0x0b, 0x84, 0x34, 0xb9, 0x58, 0x33, 0x41, 0x7c, 0xa0,
	0x4a, 0x66, 0x0d, 0x6e, 0x23, 0x29, 0x3d, 0x98, 0xeb, 0xf4, 0xd0, 0x75, 0x28, 0x85, 0x60, 0xda,
	0x16, 0x50, 0x0a, 0xb6, 0x0d, 0xc9, 0x10, 0x26, 0xfc, 0x86, 0x08, 0xf1, 0x73, 0xb1, 0x97, 0x64,
	0xe6, 0xa6, 0xe6, 0x97, 0x96, 0x80, 0xbd, 0xc4, 0xab, 0xa4, 0xc9, 0x25, 0x89, 0xae, 0xc8, 0x25,
	0x35, 0x27, 0xb5, 0x24, 0x15, 0xd5, 0x1b, 0xc0, 0xd0, 0x50, 0x32, 0xe2, 0x12, 0x44, 0x52, 0x1a,
	0x0c, 0x0e, 0x18, 0xb4, 0x00, 0x03, 0x1a, 0x9f, 0x9c, 0x9f, 0x57, 0x92, 0x9a, 0x07, 0x31, 0x9e,
	0x47, 0xc9, 0x0d, 0xc5, 0xeb, 0x10, 0x3d, 0x50, 0x57, 0x6b, 0xc3, 0x03, 0x17, 0xe2, 0x6c, 0x69,
	0xac, 0xce, 0x86, 0x68, 0x51, 0x52, 0xc7, 0x62, 0x0e, 0x46, 0x58, 0x83, 0x1c, 0xe9, 0xce, 0x25,
	0x81, 0x5d, 0x21, 0x30, 0xb0, 0x49, 0xb1, 0xd1, 0x49, 0x93, 0x4b, 0x3c, 0x39, 0x3f, 0x57, 0x2f,
	0x29, 0xb1, 0x38, 0x23, 0x5f, 0x0f, 0x94, 0x90, 0xe0, 0x8a, 0x9d, 0xf8, 0x82, 0x80, 0x5c, 0x98,
	0xf2, 0x00, 0x27, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xbb, 0x24, 0xe4, 0x68, 0x02, 0x00,
	0x00,
}
